# Generated by Django 4.2.7 on 2023-11-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_and_cat_adoption_app', '0002_alter_pet_age_alter_pet_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='status',
        ),
        migrations.AddField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending')], default='available', max_length=25),
        ),
    ]
