# Generated by Django 4.2.7 on 2023-11-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_and_cat_adoption_app', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(max_length=2500),
        ),
    ]
